#url: https://www.x-n.pw
title: xhochn private space
author: Felix FrÃ¶schlin
email: github@x-n.pw
description: > # this means to ignore newlines until "baseurl:"
  My private github page

theme: minima
markdown: kramdown
encoding: UTF-8
lang: de_DE

show_excerpts: false
google_analytics: UA-137522563-1

minima:
  date_format: "%Y-%m-%d %H:%M"
  social_links:
    github: xhochn
    linkedin: felix-froeschlin-00ba0bb0
    rss: rss

github: xhochn
linkedin: felix-froeschlin-00ba0bb0

social:
  name: Ben Balter
  links:
    - https://www.linkedin.com/in/felix-froeschlin-00ba0bb0/
    - https://github.com/xhochn
    - https://keybase.io/xhochn

header_pages:
 - about.md

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
